Python 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> # wat is het kleinste getal?
... 
... # een functie waarmee je het kleinste getal in een lijst bepaalt.
... 
... lijst = (5,1,6,2,10)
... 
... kleinste = lijst(0)
... 
... for getal in lijst:
...     if (getal < kleinste):
...         kleinste = getal
... 
... 
... print(kleinste)
>>> [DEBUG ON]
>>> [DEBUG OFF]
